import { NextResponse } from "next/server";
import { requireUserId } from "@/lib/server/auth";
import { getConfig } from "@/lib/server/config";
import { getCaseStore, isDbMissingError } from "@/lib/server/demo-data";
import {
  deleteDetection,
  getAdminClient,
  listDetections,
} from "@/lib/server/supabase-admin";
import type { DiagnosisResult } from "@/types/api";

/** Demo / auto-generated cases that should not appear in historial. */
function isAutoGenerated(c: DiagnosisResult) {
  if (c.demo) return true;
  const det = c.agent_trace?.find((t) => t.agent === "Disease Detector");
  if (det?.status === "demo") return true;
  // Detección enlatada del modo demo (siempre Sigatoka Negra @ 94%)
  if (
    (det?.status === "fallback-demo" || det?.status === "demo") &&
    c.detection.disease === "Sigatoka Negra" &&
    Math.round(c.detection.confidence * 100) === 94
  ) {
    return true;
  }
  return false;
}

export async function GET() {
  const { userId, error } = await requireUserId();
  if (error || !userId) return error!;

  const cfg = getConfig();
  const client = getAdminClient(cfg);
  const memory = getCaseStore();

  // Purge auto-generated demo cases from memory
  for (const [id, c] of [...memory.entries()]) {
    if (isAutoGenerated(c)) memory.delete(id);
  }

  if (client) {
    try {
      const dbCases = await listDetections(client, userId);
      const auto = dbCases.filter(isAutoGenerated);
      const real = dbCases.filter((c) => !isAutoGenerated(c));
      // Delete auto-generated rows so they don't come back
      for (const c of auto) {
        try {
          await deleteDetection(client, userId, c.id);
        } catch {
          /* best-effort */
        }
      }
      return NextResponse.json(real);
    } catch (e) {
      if (!isDbMissingError(e)) {
        /* fall through to memory */
      }
    }
  }

  const cases = [...memory.values()]
    .filter((c) => !isAutoGenerated(c))
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  return NextResponse.json(cases);
}
